export const lightTheme = {
  background: "white",
  primary: "#4280DD",
  secondary: "#6E9CE0",
  active: "#B3E3FF",
  highlight: "#00A3FF",
  primaryShadow: "#003D99",
  primaryText: "white",
  secondaryText: "black",
  mainText: "black",
  faded: "#FAFAFA",
  button: {
    primary: "#4280DD",
    text: "white",
    shadow: "#003D99",
    active: "#EFEFEF",
  },
};
export const darkTheme = {
  background: "black",
  primary: "#092753",
  secondary: "#545454",
  active: "#B3E3FF",
  highlight: "#8C8C8C",
  primaryShadow: "#4478B5",
  primaryText: "black",
  secondaryText: "white",
  mainText: "white",
  faded: "#323232",
  button: {
    primary: "#092753",
    text: "white",
    shadow: "#4478B5",
    active: "#EFEFEF",
  },
};
